name: Bot deploy from main

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - iac/**
# AK TODO test
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  apply-terraform:
    name: Deploy new infra to gcloud and atlas
    uses: ./.github/workflows/sub-apply-terraform.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

  deploy-telegram-bot:
    needs: apply-terraform
    name: Deploy new version of bot bakcend
    uses: ./.github/workflows/sub-deploy-telegram-bot-api.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

  deploy-subscribers-api:
    needs: apply-terraform
    name: Deploy new version of bot bakcend
    uses: ./.github/workflows/sub-deploy-subscriber-api.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

  deploy-products-api:
    needs: apply-terraform
    name: Deploy new version of bot bakcend
    uses: ./.github/workflows/sub-deploy-product-api.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}