name: Bot deploy main

on:
  push:
    branches:
      - main
    paths:
      - src/**
# AK TODO test
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  apply-terraform:
    name: Deploys new infra to gcloud and atlas
    uses: ./.github/workflows/reusable-apply-terraform.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

  deploy-to-cloudrun:
    needs: apply-terraform
    name: Deploys new version of telegrofler bot to main
    uses: ./.github/workflows/reusable-deploy-cloudrun.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
